### ISSUE TITLE
プルリク作成時、マージ時に通知ができない

### ISSUE THREAD

**Issue by safari029** [cm-hirano-shigetoshi/CodeCommitNotification#1]
以下のエラーがでており、うまく動かなかったようなのであげておきます。
```
[ERROR] IndexError: list index out of range Traceback (most recent call last):   File "/var/task/codecommit_notification.py", line 25, in lambda_handler     mention, event['detail']['author'].split(":")[1])
[ERROR] IndexError: list index out of range Traceback (most recent call last):   File "/var/task/codecommit_notification.py", line 38, in lambda_handler     event['detail']['author'].split(":")[1])
```

**Comment by safari029** [comment]
pull req だしておきました。

**Comment by cm-hirano-shigetoshi** [comment]
ありがとうございます！
内容確認してみます。

**Comment by cm-hirano-shigetoshi** [comment]
マージしました。
ありがとうございました。
